-- phpMyAdmin SQL Dump
-- version 3.4.5
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Feb 18, 2014 at 07:17 AM
-- Server version: 5.5.16
-- PHP Version: 5.3.8

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `helpinghand`
--

-- --------------------------------------------------------

--
-- Table structure for table `faqs`
--

CREATE TABLE IF NOT EXISTS `faqs` (
  `name` text NOT NULL,
  `question` text NOT NULL,
  `ip` text NOT NULL,
  `sno` int(11) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `answer` text NOT NULL,
  `status` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`sno`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=245 ;

--
-- Dumping data for table `faqs`
--

INSERT INTO `faqs` (`name`, `question`, `ip`, `sno`, `date`, `answer`, `status`) VALUES
('Sreevardhini', 'What would we can  do as a volunteer of HELPING HANDS rather than representatives ?', '10.4.15.10', 1, '2012-10-16', 'If you register as a representative you can act as a member from your class/cluster for money collection on regular schedule . If you register as a Volunteer , Helping Hands utilizes your service in future. For example while conducting health camps we need so many organizers(volunteers).', 1),
('M.venkateswara rao', 'how can we help other people from helping hands?', '10.2.6.114', 10, '2012-10-16', 'At present we are focusing on our students who need help. Based on the amount we have, we extend our service for outside charity', 1),
('suresh ', 'sir helping hand serve the food package to sneha rites  ones in year.If we gave them to monthly food service there will be happy because they are all small childrens so please serve them.', '10.2.23.47', 15, '2012-10-16', 'Definitely we do what we can do', 1),
('FROM PUC-2', 'Respective sir,u provided already a washing machine for Disability''s sir.but we have not any information about that.So e have to face a lot of problems sir.so please a conform decision about Disability''s sir.', '10.2.38.86', 17, '2012-10-16', 'It is already fixed before 3 months. Physically challenged people are using the washing machine and we sent a information to Puc students when they have to utilize the washing machine. To get more clarity about it please contact your Batch representative.', 1),
('FROM P1', 'when will you collect the helping hands money ?', '10.2.20.35', 22, '2012-10-16', 'already drop boxes are arranged for your valuable contribution. Manual collection will be started after this end sem exam', 1),
('prasad', 'will you appoint new representatives or the old representatives will be continued....?', '10.2.23.52', 24, '2012-10-16', 'it is not the point of old or new, we need the service minded people. We appreciate, if u r interested to be a volunteer.', 1),
('N110715', 'HOW YOU WILL APPOINT THE NEW REPRESENTATIVES .THEN OLD REPRESENTATIVES ARE MAY REPLACE ? PLEASE TELL ME HOW YOU ARE APPOINT US?', '10.2.23.47', 29, '2012-10-15', 'it is not the point of old or new, we need the service minded people. We appreciate, if u r interested to be a volunteer.', 1),
('kappa-12', 'How many students got help from our helping hands?', '10.2.12.124', 45, '2012-10-16', 'you might have not attended the helping hands awareness camp. there we displayed everything.', 1),
('From PUC-1', 'Dear sir,I request you to collect the money as early as possible.', '10.2.19.17', 46, '2012-10-16', 'thank you. For your kind information, drop boxes available for your valuable contribution. very soon manual collection will be started after your end sem exams', 1),
('SK.SALAM', 'WHAT ARE THE DUTIES OF THE VOLUNTEERS?', '10.2.2.44', 47, '2012-10-16', 'volunteer should not feel it as duty, but has to feel as responsibility towards the people who need our help', 1),
('GRR', '\r\nwhat is the  \r\ndifference between volunteer and representive?\r\nand their duties..?\r\n', '10.4.3.66', 48, '2012-10-16', 'Every one in the helping hands is a volunteer working for the needy people. For the smooth running and effective service, we formed representatives and executive committee  .   ', 1),
('Sk.Munni', 'what are the qualities of representative', '10.2.32.36', 50, '2012-10-16', 'Service minded nature', 1),
('E-3', 'please keep money details....so the people can understand how the H.H organization spending.......for the needy people....and as early as possible keep the washing machine available to all. ', '10.3.13.62', 51, '2012-10-16', 'Helping hands maintains 100 % transparency in money issues. they can be displayed in the website. Washing machines are installed already ', 1),
('Shiva.P', 'What are the activities that are going to be conducted by "HELPING HANDS"?', '10.3.31.75', 53, '2012-10-16', 'Based on the budget and feasibility , Executive committee will decide the activities.', 1),
('kappa-12', 'Do any P.H.C candidate need help in this year?', '10.2.12.136', 54, '2012-10-16', 'Its our responsibility to support in all the ways when they need.  ', 1),
('FROM PUC-1', 'RESPECTED SIR, WHEN WILL U COLLECT THE MONEY?.', '10.2.19.17', 60, '2012-10-18', 'thank you. For your kind information, drop boxes available for your valuable contribution. very soon manual collection will be started after your end sem exams', 1),
('E-3', 'what are the activities you are going to do,and how you are elocating 20% fund to the activities please mention...', '10.3.28.62', 63, '2012-10-20', 'Based on the budget and feasibility , Executive committee will decide the activities.', 1),
('E-3', 'you elocated 8% for the annual function.....that means if our organization collected 3 lakshs per year........for annual function 24,000/- is allocated...is it correct...to elocate that much money for that purpose.....i thought 2-3 thousend is enough...\r\n', '10.3.28.62', 64, '2012-10-20', 'It doesn''t mean that we waste the money. In the last function we bought the washing machines. Its a part of the annual function fund. In the same way, we spend 8 % of fund. ', 1),
('Rule of daily needs.', 'in daily needs i am saying about 9 th point.. just example let us take if the maximum members are 4 in house...only father is working as labour or something..per day he will get 200-250. per month we have 30 days...suppose he didn''t do work 5 days  in month.then total working days 25....his monthly income is 5,000....so his family income per head for every month is 1250...then you wont give money for him who is belongs to that family. am i right......or any special cases are there..if you have mention properly....', '10.3.28.62', 65, '2012-10-20', 'H.H providing Rs. 100-150 per head for the students whose family can''t even arrange to their children. In your case, the student won''t get the money for the daily needs, but if he gets any health problem requiring the more than Rs 1000, H.H definitely support him.', 1),
('e-2', 'provide try cycles for physically challenged people....one person daily going on his foots,and hands support.......one month before you said with them we will provide. but there is no response from the organization..', '10.3.28.62', 66, '2012-10-20', 'It is in your hand. The more the money the kind hearted one''s donate, the more the support we can give to them.', 1),
('representative.....system', 'awareness camp helping hands is conducted before 2 months.....still you are not selected representative system.........can you do  fast........it is better for all....', '10.3.28.62', 68, '2012-10-20', 'Very sorry for the delay. Due some practical problems involved, we couldn''t do it on time. We are planing the recruitment after this end sem.', 1),
('ALAMPALLI VENKATESH, K-6,P-1', 'HOW CAN WE GIVE MONEY TO HELPING HANDS?', '10.2.6.114', 74, '2012-11-06', 'thank you. For your kind information, drop boxes available for your valuable contribution. very soon manual collection will be started after your end sem exams', 1),
('M Tarakesh', 'how much money collected by last year?\r\nhow do we spent that money?', '10.2.33.11', 77, '2012-11-13', 'Please contact your class HelpingHands representative he will give the details of it.', 1),
('Ashok kumar (PUC-2)', 'Helping hands provides so much money to the people who is need.Please provide the "tricycles" and "washing machines" for "physically handicaped".', '10.2.26.35', 84, '2012-11-19', 'yes, they need but already it was happened. Try cyles were distributed and also washing machine.', 1),
('PUC-2', 'Is helping hands helpful to other than RGUKT students? ', '10.2.26.149', 89, '2012-12-01', 'yes, why not, but it is depending on the source of money allocated for that purpose.(whatever we will do outside of the college those will come under outside activities part)', 1),
('E-3', 'Helping Hands organization said we will give try cycles to the physically challenged people still there is no information about it. you announced on helping hands aniversary day. that means 3 months later....now what is your answer about it sir...', '10.3.13.62', 90, '2012-12-03', 'on February 4 th try cycles are distributed to those who need.', 1),
('collection of money.', 'when the weekly money collection is going on you stopped and brought new system before 3 months but still there is no information about it. when you are going to start money collection process in the class romms.', '10.3.13.62', 91, '2012-12-03', 'yes, but to frame the structure of helpinghands we stop the process. But, now the money collection process is going on in class rooms. ', 1),
('E-2', 'how much amount spent by helping hands after the annivesary of it?', '10.3.13.62', 93, '2012-12-03', 'With in two days we will update. to see the details please visit our helping hands organization website.', 1),
('Pavan', 'When the transactions page will be activated sir?', '10.3.5.55', 96, '2012-12-05', 'very soon it will be done. sorry for the delay.', 1),
('sri', 'Sir you said you bought washing machines, but they are now useless. please make a note that  at least the suffered can use them.  ', '10.3.36.137', 103, '2012-12-08', 'sorry for saying, do not say it is use less. because our HELPINGHANDS organization brought only one washing machine. All physically challenged people(from E-3 to PUC-1 boys) are using it in I-2 block. for girls one washerwomen is  washing their cloths. Because of Mis-communication you may not reach that point. from this time onwards you can get all details in website.  ', 1),
('N100575', 'sir,i am the h.r of my class...in my absence(when i went to home) somebody had come and elected one person among registered volunteers, but i registered as h.r in the past..then who will going to act as representative of our class sir? ', '10.3.12.179', 105, '2012-12-11', 'We don''t know how it is happened, first you say with your batch executive member, he will inform to us. later we find the solution for it.', 1),
('Shaik Ruksana puc1', 'Sir yesterday one of members from helping hands came and told us to collect money which will be collected in night sections but the persons dint explain us whether we have to maintain a list of children who has given money or not. So sir we want to know the terms and rules that we have to maintain while collecting money.', '10.2.19.54', 107, '2012-12-12', 'No need to maintain each person details of class. you have to maintain the details as we mentioned in the website in finance( money collection ) process. just i am suggesting you please go through website once again clearly.', 1),
('Laxmi', 'sir,Do u think that collecting money by DROP BOXES are satisfied?', '10.5.35.123', 109, '2012-12-13', 'The main aim of keeping drop boxes is those who forgot to bring money on tuesday  , they can drop their contribution in drop boxes whenever they want. ', 1),
('N090492', '\r\nwe are habituated to give money on saturday nights\r\nbut you changed and everyone is ignoring drop boxes or forgetting to drop money\r\nIts nice idea but along with it keep going on collecting money every saturday night\r\nOtherwise defficiency may arise...\r\n', '10.3.16.136', 111, '2012-12-14', 'yes, but now weekly collection  is happening. but only the change is  Because of many members  suggestion, Representatives collecting the  money on every week of tuesday.', 1),
('From E2 student', 'Is it possible for us to have large scale service from our "RGUKT HELPING HANDS"?', '10.5.38.51', 114, '2012-12-14', 'we don''t know in your mind what is large scale. But our HelpingHands organization spent lakhs of money on different activities(Health problem students, daily nedds, transport charges, dhobicharges, giving money to outside charity, conducting blood camp...etc) and at the same time our students & others contributed lakhs of money to our HelpingHands organization. that means i think it is a large scale service only. for more clarity contact your class helpinghands representative.', 1),
('SAI', 'What is the main aim of helping hands?', '10.2.27.163', 115, '2012-12-18', ' Apart from education we can also respond and participate in social service of our society. ( but first preference is our students later basing on source money we will do out side charity)', 1),
('kappa-11', 'WHEN THE EYE CAMP WILL BE HELD, SIR?', '10.2.11.116', 119, '2012-12-20', 'As early as possible Helping Hands organization going to conduct a MEGA HEALTH CAMP. In this camp Eye check up also there. further more details about this check our website daily.', 1),
('Y.Chitti Raju', 'Sir, Why did you stop the money collection weekly?', '10.2.18.44', 121, '2013-01-05', 'Yes,But now it is going on... Helping Hands committee decided that Collection of the money will be happen from the students every month on second Thursday But many members of representatives said that it is good collecting the money every week itself. so we change the process, that''s why now weekly collection is going on. ', 1),
('E1', 'SIR,I AM THE STUDENT OF E1.IN MY CLASS SO MANY MEMEBERS ASKING ME HOW CAN WE GIVE MONEY EVERY WEAK ALTHOUGH THEY ARE RICH THEY ARE ASKING LIKE THAT\r\nIS AWARENESS CAMP IS CONDUCTED THEY WONT COME THERE HOW CAN I EXPLAIN THEM PLEASE ARRANGE SOME MEMBERS TO TELL GREATNESS OF THE HELPING HANDS TO ALL IN THEIR CLASSROOMS ', '10.3.2.89', 124, '2013-01-10', 'From starting onwards our HelpingHands organization saying that it is not mandatory to give money every week. Announce This Matter in your classroom. and when ever we updated finance details of helping hands then announce in your Class room..please go through web site.', 1),
('D.Venkata Abhinav', 'When would the volunteers list be put up on the site ?', '10.3.3.212', 126, '2013-01-22', 'you can see those list in our Helpinghands website (in people option)', 1),
('B.PRANAY KUMAR', 'I think it is better to collect the money twice a month.', '10.2.8.102', 127, '2013-01-23', 'Already Helping Hands committee decided that Collection of the money will be happen from the students every month on second Thursday But many members of representatives said that it is good collecting the money every week itself. so we change the process, that''s why weekly collection is going on. anyway we will consider your opinion also for next time.', 1),
('E3', 'WHY ARE YOU NOT UPDATING THE MONEY DETAILS SIR\r\nALL STUDENTS WANT TO SEE THE MONEY DETAILS', '10.3.2.29', 130, '2013-02-05', 'With in two days we will update about collecting and spending details of this year ', 1),
('P1 ', 'SIR, PHYSICAL HANDICAPPED students cannot wash their clothes about their disability The campus would arranged a washing machine to wash disability student clothes but daily disability students cannot come to B.TECH campus to wash their clothes so I request you to arrange a washerman to wash for PUC Disability students', '10.2.11.26', 131, '2013-02-06', 'definitely we will discuss this issue with Helpinghands organization committee and we will take best solution for them.', 1),
('K-11', 'P1 physical challenger men cannot wash clothes so we cannot come B.TECH Campus to give our clothes daily hence we are requested you to arrange us a washerman ', '10.2.11.26', 132, '2013-02-06', 'definitely we will discuss this issue  with Helpinghands organization committee and we will take best solution for them', 1),
('PUC-2', 'When will you give the full details about money collection in previous years?', '10.2.24.36', 133, '2013-02-07', 'very soon we will update about our HelpingHands organization  spent details of past.  so you can refer. ', 1),
('P-2 student', 'It is better to collect money twice per month?', '10.2.33.78', 137, '2013-02-16', 'Already Helping Hands committee decided that Collection of the money will be happen from the students every month on second Thursday But many members of representatives said that it is good collecting the money every week itself. so we change the process, that''s why weekly collection is going on. anyway we will consider your opinion also for next time.', 1),
('T.SHANMUKHA SRINIVAS', 'What I have to do as a volunteer? I think it is not better to give helping hands money to unuseful activites.(cultural activities).some people don''t has good opinion on it.so explain in every class for which things you''re spending money!then they realized and they agree that helping hands is one great organisation.money collectors should explain about helping hands while they went to collecting money.', '10.2.5.131', 138, '2013-02-19', 'Sorry to saying that, whatever you said it is wrong. HelpingHands organization is not giving any single paise to Cultural activities. you can contact your class helpinghands representative and you can ask whatever you want know about our HelpingHands organization. ', 1),
('puc-2', 'Sir,i have one small doubt.sir how can you select the new EC members.what are the qualities of EC members?', '10.2.40.65', 139, '2013-02-19', 'Those who are elected for execution committee they must have a experience one year as a representative of HELPINGHANDS organization. If many members are came, then helpinghands committee will ask some questions regarding social services and about our organization. In this process who gave best solutions and answers about questions that person will work as a member of EC.', 1),
('M.ashok ', 'sir physical handicapped dont  wash their clothes. we can''t come B.TECH .That,s why we are requested arranged washerman', '10.2.19.58', 140, '2013-02-20', 'Helping hands committee decided to bring two new washing machines for physically challenged people(one for girls& another for Puc). But this must be accept by our Director sir, so will take this issue to Director sir.', 1),
('PUC2 batch students', 'Sir,please updating the previous money details till tuesday. ', '10.2.31.53', 141, '2013-02-21', 'definitely we will update but it takes one week time.. after that we will update.. for more details please post your question.', 1),
('Puc-2', 'When will you start eye camp?', '10.2.31.53', 142, '2013-02-21', 'Today we are going to take survey on health camp, then we will submit the details and with in one week Helpinghands will conduct health camp.', 1),
('MADHAVA', 'Dear sir,What is the decision that you have take to collect the money week wise , month wise or what ever the moment that we we want?', '10.2.11.132', 143, '2013-02-21', 'Already Helping Hands committee decided that Collection of the money will be happen from the students every month on second Thursday But many members of representatives said that it is good collecting the money every week itself. so we change the process, that''s why weekly collection is going on. for more clarity contact your class helpinghands representative. ', 1),
('E1', 'Sir, can we get the volunteer''s list.You said to check it in the people''s option.But it wasn''t.', '10.3.31.30', 144, '2013-02-22', 'Yes..Very soon volunteers list will be updated.', 1),
('siva k11', 'when will you start eye camp?', '10.2.11.26', 145, '2013-02-22', 'Our Helpinghands organization going to conduct a Mega Health camp. In this camp eye and ent etc...checkups are there... today we will take survey from the students after that within one week  we will try to keep health camp.', 1),
('Sowmya.', 'sir,when we give money to H.Rs? tuesday or thursday?', '10.2.15.21', 146, '2013-02-22', 'your contribution have to give on tuesday. HR will submit your class money to cluster or branch representative on tuesday night it self. ', 1),
('E-3', 'some representatives are not taking it as responsibility....they are not intimating anything in class rooms.', '10.5.16.113', 147, '2013-02-22', 'we will try to keep meeting with representatives and we will discuss these points with them.', 1),
('E-1', 'before 20 days onwards washing machine was not working.......we intimated to Helping Hands committee members but they are not responding sir, take necessary action about it as early as possible.', '10.5.16.113', 148, '2013-02-22', 'very soon it will repair...', 1),
('MADHAVA', 'Dear sir, in the medical survey some of us don''t know about the meaning of ENT. what does it mean?', '10.2.11.132', 150, '2013-02-23', 'ENT is combination of Ear,Nose and Throat.', 1),
('madhava', 'Dear sir, could you humbly inform that, what are the eligible qualities to gain help from  our HELPING HAND organization? ', '10.2.11.132', 151, '2013-02-23', 'He must be a poor. That is enough to get help from Our Helpinghands organization.', 1),
('KAPPA-11', 'Sir, did helping hands take news papers and rough papers? Isn''t true or not?If collected in how we give papers to helping hands?', '10.2.11.116', 153, '2013-02-25', 'Yes, HelpingHands Representatives will collect rough books and waste newspaper from the students. yearly once or twice we will take from the students.depending on the time we will do it, and whenever we are going to do this process we will intimate to all the students. we try to keep one room for this purpose by asking our college administration. ', 1),
('omega-3, p -1', 'will you please tell us when will you conduct the MEGA HEALTH CAMP ,sir?', '10.2.15.83', 154, '2013-02-25', 'we will intimate to you....', 1),
('SIVA KUMAR K-11', 'Sir what is the main aim of helping hands please explain this question sir ', '10.2.11.26', 155, '2013-02-27', 'Apart from education we can also respond and participate in social service of our society. ( but first preference is our students later basing on source money we will do out side charity)', 1),
('madhava', 'when will be the MEGA HEALTH CAMP is going to held?\r\n', '10.2.11.132', 156, '2013-03-01', 'Due to lack of time we decided to conduct health camp after this semester.', 1),
('M.Praveen', 'The puc students are not giving the money fullfilly', '10.2.20.73', 157, '2013-03-01', ' Its not a mandatory to give money to Helpinghands organization. Its their wish to donate or not. if we expose our activities, definitely they will contribute money to our Helpinghands organization.', 1),
('N120516', 'Respected sir, I want to become a batch representative. What shall I have to do?', '10.2.11.113', 158, '2013-03-02', 'As like every social organization HelpingHands also have rules&regulations so must follow the rules, no one is exception. Whenever we are going to change Batch representative we will intimate to you.', 1),
('puc-1', 'when will we get the volunteer''s list,sir?', '10.2.15.21', 160, '2013-03-04', 'Any way We updated executive members, representatives of Helpinghands organization. We got large member of list as volunteers for that  we didn''t displayed. If it is possible we will displayed.', 1),
('E2 Mech', 'I Want to know how much money is deposited in our helping hands account?????', '10.3.40.68', 161, '2013-03-04', 'Very soon we will update, any way ask your class Helping Hands representatives.', 1),
('P1', 'Sir, you are collecting money as weekly. some of the students feels this like a burden.\r\nSo request you to change this process as "once" or "twice" a month.', '10.2.15.51', 162, '2013-03-05', 'Helping Hands committee decided that Collection of the money will be happen from the students every month on second Thursday But many members of representatives said that it is good collecting the money every week itself. so we change the process, that''s why now weekly collection is going on. anyway it''s not a mandatory to give every week, it their wish to contribute every week or not.', 1),
('HR', 'Excuse me sir, In our class room our classmets asks me to give a speach about HELPING HANDS. I''m explained them what i know.I''m requestin you to arrange HR''s meeting once per every two months to suggest my friends. ', '10.2.15.51', 163, '2013-03-05', 'we will discuss about it in our Helpingahands executive committee. ', 1),
('p1', 'sir plese arrange the washerman for P.H.C why because phc''s  faced the lot of problems for washing clothes. plese sir ', '10.2.18.177', 164, '2013-03-05', 'we said with washer men. and with in two or three days he will wash cloths of Physically challenged people.', 1),
('K8', 'When will be the money collections of this week updated sir?', '10.2.8.102', 169, '2013-03-08', '', 1),
('kappa-8', 'sir we will give you support and please arrange an awareness about the condition of this earth and globalization.sir i think that helping hands is not only for the  health and other supports it should also give a bright future.it should help the nature.', '10.2.8.121', 170, '2013-03-08', 'we will think, and definitely we will try to do.', 1),
('puc-1', 'Sir, thank you for giving money of 1000/- to the poor girl students.  We hope helping hands improve in future as a big association. All the best to our helping hands.', '10.2.11.116', 171, '2013-03-11', 'We convey your thanks and wishes to all who contributed  money and service in HH. ', 1),
('Engg 1 Student', 'Washing Machines are being misused. Some are using them in the name of those who are eligible to use them. And those who are eligible also helping their friends to use washing machines. So try to focus on this problem and save helping hands from misusing. Because Its all students'' property.', '10.3.13.250', 230, '2014-02-04', 'We came to know this problem and introduced maintenance book for washing machine under the guidance of warden.And if you found any misuse, please inform us. ', 1),
('Puc-2', 'Sir , the drop box near puc canteen (near Mu classes) getting old . If we drop, money in that how can you collect money because it is rusted.', '10.2.19.93', 236, '2014-02-05', 'We will try to change that box position. Soon we will find another place which is accessible to all students.', 1),
('N090327', 'Great Work.., But update the money collections every week so that we may feel interest to drop a coin in the box..,', '10.3.15.221', 237, '2014-02-06', 'Yes, We will update money collections every week.', 1),
('P1', 'sir please spent some money for daily needs of poor students.because they have not money and please update the weekly collections.', '10.2.26.80', 239, '2014-02-14', '', 0),
('PUC', 'Sir, I think PUC students are uninterested in giving money to helping hands, so please motivate them.', '10.2.41.45', 240, '2014-02-15', '', 0),
('srinivas nayak', 'sir really it is good wonder thought to start helping hands organisation, we should help to developthis organisaton ,we are feeling so good,one more question sir actually whose thought it to start the helping hand organisation', '10.2.39.29', 241, '2014-02-15', '', 0),
('PUC-1', 'Helping hands is very helpful for students to meet their needs. it would be more successful if initiation taken by H.R''s is some what enthusiastic.', '10.2.37.65', 243, '2014-02-17', '', 0),
('Satya', 'Show it in work', '10.4.3.140', 244, '2014-02-18', '', 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
